### ISSUE TITLE
Poly/ML prepends an unexpected newline to the standard input stream:

### ISSUE THREAD

**Issue by eduardoleon** [polyml/polyml#1]
I wrote the following program, which reads lines from the standard input, and writes them verbatim to the standard output:

```sml
structure T = TextIO

fun main () =
  case T.inputLine T.stdIn of
      NONE => ()
    | SOME x => (print x; main ())
```

When I run it, something strange happens:

```
$ polyc -o cat cat.sml
$ ./cat

foo
foo
bar
bar
qux
qux
^C
$
```

And another test case:

```
$ ./cat < cat.sml

structure T = TextIO

fun main () =
  case T.inputLine T.stdIn of
      NONE => ()
    | SOME x => (print x; main ())
$
```

In both cases, a newline is prepended to the actual contents of the standard input. Is this really the intended behavior? It seems really strange.

**Comment by dcjm** [comment]
This is a bug that has been fixed in Git master.  You can work-around the problem in the current release by using poly with the -i option to compile and export and then using polyc for the link step:
```
echo "use \"cat.sml\"; PolyML.export(\"cat.o\", main); " | poly -i -q  --error-exit
polyc -o cat cat.o
```
