### ISSUE TITLE
5.5.2: fixupConstantLoad error using Poly/ML configured with `--with-portable`

### ISSUE THREAD

**Issue by Hibou57** [polyml/polyml#10]
I got the error below, using Poly/ML configured with `--with-portable`. The error disappeared when I used a Poly/ML configured without this option.

    Linking boolScript.uo to produce theory-builder executable
    Poly/ML 5.5.2 Release
    Exception- InternalError: fixupConstantLoad: constant too distant (16-bit offset) raised while compiling
    
    Exception- InternalError: fixupConstantLoad: constant too distant (16-bit offset) raised while compiling

Initially reported as an HOL4 build issue, here: [Build fails with PolyML 5.5.2](https://github.com/HOL-Theorem-Prover/HOL/issues/324).

**Comment by dcjm** [comment]
The interpreted version can only handle compiled functions of up to 64kbytes.  It may be possible to relax this in the future but it is always preferable to use the native code-generator.
