### ISSUE TITLE
Commit ba30d74e9b533d3def10e663a5b436c53b97ba4e breaks address arithmetic

### ISSUE THREAD

**Issue by pclayton** [polyml/polyml#101]
This issue occurs on Linux x86_64 (where pointers are 8 bytes).  See example [test_addr_arith.tar.gz](https://github.com/polyml/polyml/files/1903181/test_addr_arith.tar.gz) - run make to build the shared object library.

**Comment by dcjm** [comment]
I've pushed a commit ba30d74 that seems to have fixed this.  The 32-bit load in cUint was instead using a 64-bit load so the high-order 32-bits in `size()` were garbage.  This should have been picked up in the regression test but it just happened that the test was loading a value where the top 32-bits were zero.

**Comment by pclayton** [comment]
Thanks - this commit solves the issue.  I've been using this version and haven't noticed any adverse effects.
