### ISSUE TITLE
String.substring / unsafeSubstring: special case for length = 1

### ISSUE THREAD

**Issue by makarius** [polyml/polyml#106]
https://github.com/polyml/polyml/blob/04ba1833de85388cde2d6aa831ef2396fda1010b/basis/String.sml#L1348

Like String.str, it would be nice if String.substring would lookup the static table of singeleton strings.  Presently I have this odd workaround in Isabelle/ML:

structure String =
struct
  open String;
  fun substring (s, i, n) =
    if n = 1 then String.str (String.sub (s, i))
    else String.substring (s, i, n);
end;

Note that there is also a byte vector operation, using the same unsafeSubstring at the bottom.

**Comment by dcjm** [comment]
I've now changed this in commit eb3748f ,
