### ISSUE TITLE
Test174.ML fails on armhf, armv7 and aarch64

### ISSUE THREAD

**Issue by nmeum** [polyml/polyml#110]
I packaged polyml for Alpine Linux (which uses musl libc) and just upgraded it to 5.8 while doing so I noticed that the testsuite for 5.8 doesn't pass on armhf, armv7 and aarch64 (on aarch64 the build even seems to fail). However, the 5.7.1 test suite did pass on these architectures.

Unfortunately, I personally don't have access to any of these platforms I simply have the buildlogs generated by the Alpine Linux package builders:

* [aarch64-polyml-5.8-r0.log](https://github.com/polyml/polyml/files/2956501/aarch64-polyml-5.8-r0.log)
* [armhf-polyml-5.8-r0.log](https://github.com/polyml/polyml/files/2956502/armhf-polyml-5.8-r0.log)
* [armv7-polyml-5.8-r0.log](https://github.com/polyml/polyml/files/2956503/armv7-polyml-5.8-r0.log)

**Comment by nmeum** [comment]
For ppc64le the build also fails:  [ppc64le-polyml-5.8-r0.log](https://github.com/polyml/polyml/files/2956542/ppc64le-polyml-5.8-r0.log)

**Comment by myfreeweb** [comment]
> aarch64 the build even seems to fail

> make[2]: *** [Makefile:1161: polyexport.o] Aborted

yeah, actually **5.7.1** fails for me on the same `polyexport` file on FreeBSD/aarch64 :(

**Comment by nmeum** [comment]
`Test174.ML` no longer segfaults for me on armhf/armv7 musl. `USE_PTHREAD_SIGNALS` also doesn't exist anymore. However, `Test160.ML` segfaults on armhf and armv7 nowadays (polyml-5.9). Will try to get access to an arm machine to obtain a backtrace.

**Comment by nmeum** [comment]
```
$ uname -a
Linux edge-armv7 5.15.32-0-lts #1-Alpine SMP Mon, 28 Mar 2022 13:09:00 +0000 armv8l Linux
$ ./poly --use Tests/Succeed/Test160.ML
val dv = fn: int * int -> int
val md = fn: int * int -> int
val check = fn: ''a * ''a -> unit
val it = (): unit
val it = (): unit
val it = (): unit
val it = (): unit
val random = fn: unit -> int
val doFor = fn: (unit -> 'a) -> int -> unit
val doit = fn: unit -> unit
Segmentation fault (core dumped)
```

The backtrace for the segfault looks as follows:

```
#0  0xf7ab031a in PolyObject::Get (i=0, this=0x1) at globals.h:309
#1  ByteCodeInterpreter::RunInterpreter (this=this@entry=0x397c5c, taskData=taskData@entry=0x397bf0) at bytecode.cpp:846
#2  0xf7acedf8 in IntTaskData::EnterPolyCode (this=0x397bf0) at interpreter.cpp:293
#3  0xf7ac2bf4 in NewThreadFunction (parameter=0x397bf0) at processes.cpp:1253
#4  0xf7b4e0b4 in start (p=0xed74fd58) at src/thread/pthread_create.c:203
#5  0xf7b4d972 in __clone () at src/thread/arm/clone.s:23
#6  0xf7b4d972 in __clone () at src/thread/arm/clone.s:23
#7  0xf7b4d972 in __clone () at src/thread/arm/clone.s:23
#8  0xf7b4d972 in __clone () at src/thread/arm/clone.s:23
#9  0xf7b4d972 in __clone () at src/thread/arm/clone.s:23
#10 0xf7b4d972 in __clone () at src/thread/arm/clone.s:23
#11 0xf7b4d972 in __clone () at src/thread/arm/clone.s:23
#12 0xf7b4d972 in __clone () at src/thread/arm/clone.s:23
…
```

**Comment by dcjm** [comment]
Is this with 5.9 release or with git master?

**Comment by nmeum** [comment]
> Is this with 5.9 release or with git master?

This is with the 5.9 release. If you want me to, I can also try current Git HEAD.

**Comment by dcjm** [comment]
Could you try this with Git HEAD.  This works for me on Raspberry Pi machines.

**Comment by nmeum** [comment]
Yep, can confirm that it works with Git HEAD.

Do you, by any chance, have an idea which commit might have fixed this? 🤔
