### ISSUE TITLE
Word32 / Compiler Regression?

### ISSUE THREAD

**Issue by tjark** [polyml/polyml#112]
The attached code uses `Word32` to implement 64-bit words. However, I am having trouble to understand its behavior.

**Actual behavior:**
$ poly < bug_example.sml 
[...]
val it = W64 (0wxFFFFFFFF, 0wxFFFFFFFF): W64.w64

**Expected behavior:**
$ poly < bug_example.sml 
[...]
val it = W64 (0wx0, 0wx0): W64.w64

$ poly -v
Poly/ML 5.8 Release    RTS version: X86_64-5.8 (Git version v5.8-19-g8be18a1)

Note that Poly/ML 5.5.2 still shows the expected behavior.
[bug_example.sml.zip](https://github.com/polyml/polyml/files/3019019/bug_example.sml.zip)

**Comment by dcjm** [comment]
This turned out to be a bug in the handling of Word.andb(x, 0w0) which should have reduced to 0w0.  I've pushed a fix to master (  889f7c3 ) but using it will require running "make compiler".  The problem does not occur with LargeWord.andb so only appears on native 64-bits.

**Comment by tjark** [comment]
I confirm that this is fixed. Thank you!
