### ISSUE TITLE
non-atomic operations on PLock::lockCount

### ISSUE THREAD

**Issue by Smattr** [polyml/polyml#118]
When the debug option `DEBUG_CONTENTION` is enabled a `PLock` issues debugging messages when it is heavily contented. This is done using a member variable `lockCount` that is incremented on each failure to immediately acquire a lock. AFAICT nothing prevents multiple threads being in this block modifying `lockCount` at once. In fact, by definition this is likely to happen when 3 or more threads compete for the same lock. Should this be using something like `__sync_fetch_and_add` here? Without this, you may end up with torn reads/writes on some platforms.

**Comment by dcjm** [comment]
That's true but it's probably not worth it.  The idea is to narrow down the search when contention is suspected rather than get an absolute figure.  It has been used in the past and works well enough.

**Comment by Smattr** [comment]
OK. I think this is technically undefined behaviour but an instance the compiler is unlikely to take advantage of.
