### ISSUE TITLE
Regression in space usage

### ISSUE THREAD

**Issue by pclayton** [polyml/polyml#121]
I have a simple function that runs fine using Poly/ML 5.7.1.  Using 5.8, it runs out of stack space.  Using the latest commit on master (Git version v5.8-53-g055f20c), the example terminates but Poly/ML consumes several gigabytes of memory, which it did not do under 5.7.1, and runs about 8 times slower than 5.7.1.

**Comment by pclayton** [comment]
[This example](https://github.com/polyml/polyml/files/3993229/polyml_compiler_issue-20191222.sml.gz) demonstrates the issue.

**Comment by dcjm** [comment]
Thanks for reporting this.  I've committed a fix in 0ad5aa8 .  There was a problem with tail-recursive functions that returned tuples.  This changed because of the way tuples on the stack are handled in the 32-in-64 bit version and that affected the native address versions as well.

**Comment by pclayton** [comment]
Thanks - that fix resolves the issue.
