### ISSUE TITLE
Full evaluation at compile time ?

### ISSUE THREAD

**Issue by EmptyStackExn** [polyml/polyml#123]
Hello, I have the following small program which I want to compile into bytecode:
```
val t = print "Hello"
```
When i type `polyc` on this piece of code, it directly executes this piece of code (by outputing `Hello` on sdtout) and `./a.out` becomes useless as it just outputs nothing. On the other side, function declaration don't seem to be fully evaluated like here. Why is the value of `t` evaluated ? Is it part of a constant propagation process ? This behavior is quite different from current ML-type language compilers.

**Comment by pclayton** [comment]
Your code is run in a Poly/ML session at the time of compilation, so all top-level vals will be evaluated at compilation.  This is different to the way MLton works where I believe top-level vals will be evaluated at run time when the program starts.  With Poly/ML, output must be a side effect of your `main` function to occur at run time.

Also, there is a [mailing list](http://lists.inf.ed.ac.uk/mailman/listinfo/polyml) which may be a better forum for general discussion - I expect more people follow that than Github issues.

**Comment by EmptyStackExn** [comment]
Thanks for the reply!
