### ISSUE TITLE
mailing list?

### ISSUE THREAD

**Issue by kaveman-** [polyml/polyml#125]
the [mailing list](http://lists.inf.ed.ac.uk/mailman/listinfo/polyml) redirects to a login page. As someone who isn't subscribed to the list, how do I read the archives?

**Comment by pclayton** [comment]
There is a link to the archives in the first section of that page:

> To see the collection of prior postings to the list, visit the [polyml Archives](http://lists.inf.ed.ac.uk/pipermail/polyml/).

**Comment by kaveman-** [comment]
> There is a link to the archives in the first section of that page:
> 
> > To see the collection of prior postings to the list, visit the [polyml Archives](http://lists.inf.ed.ac.uk/pipermail/polyml/).

thanks for the link. (first section of what page?)

**Comment by pclayton** [comment]
The page that you quoted a link to:
> the [mailing list](http://lists.inf.ed.ac.uk/mailman/listinfo/polyml) redirects...
