### ISSUE TITLE
REPL messages are suppressed by loadState

### ISSUE THREAD

**Issue by eldesh** [polyml/polyml#129]
After loading the state with `PolyML.SaveState.loadState`, REPL messages will be suppressed.

```sml
$ poly
Poly/ML 5.8 Release
> open Int;
val * = fn: int * int -> int
val + = fn: int * int -> int
.
.
> PolyML.SaveState.loadState "/path/to/anystate";
val it = (): unit
> open Int;
>
```

**Comment by pclayton** [comment]
What is the value of `! PolyML.Compiler.printDepth` before and after loading the state?  If loading the state is setting the print depth to 0, you can set it to another value using `PolyML.print_depth` after loading the state.

**Comment by eldesh** [comment]
My state file was generated under `poly -q` then `! PolyML.Compiler.printDepth = 0`.
Thank you!
