### ISSUE TITLE
PolyML.objSize reports 'Bad address' and incorrect size with compat32bit

### ISSUE THREAD

**Issue by pclayton** [polyml/polyml#140]
For Poly/ML built with `--enable-compact32bit`, I see
```
> PolyML.objSize (fn () => ());
Bad address 0x7f1aa92680d0 found
val it = 3: int
```

For Poly/ML built with `--disable-compact32bit` (the default), I see
```
> PolyML.objSize (fn () => ());
val it = 15: int
```

There is also an issue with `PolyML.showSize`.

**Comment by dcjm** [comment]
Thanks for reporting this.  Should be fixed in 6ef92ae.
