### ISSUE TITLE
Foreign.Memory.++/-- do not treat the offset as signed

### ISSUE THREAD

**Issue by pclayton** [polyml/polyml#141]
In `Foreign.Memory`, the implementations of operations `++` and `--` do not sign extend the offset so it is not treated as a signed value.  As a result, the behaviour where offset are negated may not be as expected.  For example, consider the following expressions:
```
-- (null, 0w1)
```
```
++ (null, ~ 0w1)
```
I expected these to give the same result but they differ on platforms where `Word.wordSize` is less than the pointer size.  For example, using 5.8.1 on a 64 bit platform without compat32bit:
```
> Word.wordSize;
val it = 63: int
> #size Foreign.LowLevel.cTypePointer * 0w8;
val it = 0wx40: word
> open Foreign.Memory;
...
> voidStar2Sysword (-- (null, 0w1));
val it = 0wxFFFFFFFFFFFFFFFF: SysWord.word
> voidStar2Sysword (++ (null, ~ 0w1));
val it = 0wx7FFFFFFFFFFFFFFF: SysWord.word
```

**Comment by pclayton** [comment]
[MLton.Pointer](http://mlton.org/MLtonPointer) provides a similar interface and the functions `add` and `sub` treated the offset as signed.  The use of sign extension in their implementation can be seen in the [code](https://github.com/MLton/mlton/blob/master/basis-library/mlton/pointer.sml#L17).  I've checked this in a test with MLton 20130715 on a 64 bit platform and I see the output
```
Word.wordSize = 32
MLton.Pointer.sizeofPointer = 8
add (null, ~ 0w1) = sub (null, 0w1) = true
```
from the following program
```
val () = app print ["Word.wordSize = ", Int.toString Word.wordSize, "\n"]
val () = app print ["MLton.Pointer.sizeofPointer = ", Word.toString MLton.Pointer.sizeofPointer, "\n"]
val () =
  let
    open MLton.Pointer
  in
    app print [
        "add (null, ~ 0w1) = sub (null, 0w1) = ",
      if add (null, ~ 0w1) = sub (null, 0w1)
      then "true"
      else "false",
      "\n"
    ]
  end
```

**Comment by dcjm** [comment]
I've wondered about how to treat negative values in both the ++/-- operators and also the various get and set functions.  It seemed sensible to treat them in the same way.  Negative offsets don't make sense for the internal load and store functions used for ML vectors and arrays but they are meaningful for the C operations.  I've changed this so that the offsets are always treated as signed.

**Comment by dcjm** [comment]
Closing this as it should now be fixed.

**Comment by pclayton** [comment]
Confirmed - this is now fixed.

I note that 5.8.1 gives the following output on a 64 bit platform with compat32bit:
```
> open Foreign.Memory;
...
> voidStar2Sysword (++ (null, ~ 0w1));
val it = 0wx7FFFFFFF: SysWord.word
```
which differs from the output without compact32bit, as shown in the [initial comment](https://github.com/polyml/polyml/issues/141#issuecomment-688224788) above:
```
> voidStar2Sysword (++ (null, ~ 0w1));
val it = 0wx7FFFFFFFFFFFFFFF: SysWord.word
```
So I think the new behaviour is even more desirable as `++` no longer depends on whether compact32bit is enabled.
