### ISSUE TITLE
Unix.execute not working as expected under 5.8.2

### ISSUE THREAD

**Issue by acjf3** [polyml/polyml#151]
There are issues with using HOL4 under PolyML 5.8.2. This issue stems from the following file

 https://github.com/HOL-Theorem-Prover/HOL/blob/develop/tools/vim/vimhol.src

which makes use of Unix.execute.

In particular, the following

> val fifo = Unix.textInstreamOf (Unix.execute("/usr/bin/env", ["tail", "/dev/null"]));

now gives an error

val fifo = ?: TextIO.instream
> tail: '/dev/null': Permission denied

and we also get an error with

> val fifo = Unix.textInstreamOf (Unix.execute("/usr/bin/env", ["tail", "-f", "filename"]));
val fifo = ?: TextIO.instream
> tail: invalid option -- 'f'

**Comment by dcjm** [comment]
I've pushed a fix to master that should have addressed this.  If it looks all right I'll include it in fixes-5.8.2.

**Comment by acjf3** [comment]
Thanks. I've tried out the fix and the error messages have gone. However, there is a remaining issue. The problem is that it is not possible to terminate the HOL4 session as before. Perviously, we could do a Control-D to exit the REPL, whereas now Control-D causes the session to hang (all input is ignored, including Control-D and Control-C, and the process does not terminate). So it looks like something still isn't quite right here.

**Comment by dcjm** [comment]
It seems that the child process was ignoring signals and so the main process was hanging while processing the `reap `in the `atExit` function.

**Comment by acjf3** [comment]
I can confirm that things are working as expected now. Many thanks.
