### ISSUE TITLE
Foreign.LowLevel.CTypeSignedInt used for some unsigned types

### ISSUE THREAD

**Issue by pclayton** [polyml/polyml#153]
The definitions of [`cTypeUint`](https://github.com/polyml/polyml/blob/8185978a586ab759cc0d6e2eda9762c724421d86/basis/Foreign.sml#L584) and [`cTypeUlong`](https://github.com/polyml/polyml/blob/8185978a586ab759cc0d6e2eda9762c724421d86/basis/Foreign.sml#L589) use `CTypeSignedInt` but I would expect `CTypeUnsignedInt` to be used as for other unsigned types.  I am not aware of this causing any issue but thought I would raise it in case it is unintended.

**Comment by dcjm** [comment]
Thanks for spotting that; it was definitely wrong.
