### ISSUE TITLE
`PolyML.Exception.exceptionLocation` gives locations internal to the Poly/ML implementation

### ISSUE THREAD

**Issue by frou** [polyml/polyml#156]
By default, a compiled Poly/ML program that encounters an unhandled exception will exit silently with status 1.

By writing a top-level exception handler (e.g. in the `main` function) that makes use of `PolyML.Exception.exceptionLocation`, we can at least have it so that the file path and line number for where the exception was raised (though not a full stack trace) are printed to stderr before the program exits.

Unfortunately the location we get is often inside Poly/ML's implementation code, which is not particularly helpful after the fact for investigating why a given program crashed. 

* e.g.
  * If a call to the function `Posix.FileSys.stat` failed (which call?), we get the location `unix_specific.cpp:760`.
  * If a divide by zero happened (where?), we get the location `./basis/InitialBasis.ML:125`

The location which would be most helpful to get is the deepest one in user code before it dipped into the Poly/ML implementation code.

**Comment by dcjm** [comment]
If you need to get the location where an exception is being raised the best way is to use the debugger, either through [`PolyML.Debug`](https://www.polyml.org/documentation/Reference/PolyMLDebug.html) or [`PolyML.DebuggerInterface`](https://www.polyml.org/documentation/Reference/PolyMLDebuggerInterface.html).  To get the location information as you have described would require the compiler to add handlers at every place where an exception could possibly be raised.

**Comment by frou** [comment]
Thanks David. It's unfortunate because in my experience most general-purpose languages with exceptions will write actionable information when they exit due to one. 

But obviously you know about this particular implementation infinitely more than me. Feel free to close this issue if it practically is never going to happen.
