### ISSUE TITLE
Windows binary distribution nowhere to be found

### ISSUE THREAD

**Issue by ColourGrey** [polyml/polyml#158]
The PolyML site claims that "There is a binary distribution for 64-bit Windows." I have looked for it on both that site and here, on GitHub, but it seems to be so well hidden that I haven't been able to find it.

There is currently a single SML team offering a functional installation package for Windows - SML/NJ. I find this very sad.

**Comment by pclayton** [comment]
Poly/ML 5.8 seems to be the most recent release that provides an MSI file in the assets provided on Github.

Also, I note that the [downloads page](https://www.polyml.org/download.html) incorrectly claims that 5.8.1 is the latest release.

**Comment by ColourGrey** [comment]
@pclayton Indeed, you seem to be right. For other people's convenience, let me link to it here: [PolyML 5.8](https://github.com/polyml/polyml/releases/download/v5.8/PolyML5.8-64bit.msi).

**Comment by dcjm** [comment]
Thanks for reporting this.  I've uploaded a binary for Windows for 5.8.2 and also fixed the downloads page.

**Comment by ColourGrey** [comment]
Well, here I am with the same issue as 6 months ago: the download page says that "[t]here is a binary distribution for 64-bit Windows", but this binary is nowhere to be found for 5.9. Could you please include it in the "Assets" section of the 5.9 release? (And congratulations for not giving up the development of Poly/ML!)

**Comment by dcjm** [comment]
Sorry about that.  Once again I meant to do that and it slipped my mind.  Should now have been fixed.
