### ISSUE TITLE
FFI corrupts struct argument in 5.8.2

### ISSUE THREAD

**Issue by pclayton** [polyml/polyml#160]
With Poly/ML 5.8.1, I see no issue calling a C function whose argument is a struct.  With Poly/ML 5.8.2 on Linux x86_64, a C function appears to be getting incorrect values for the fields of its struct argument when the struct is more than 8 bytes.  [This example](https://github.com/polyml/polyml/files/7305799/check_align.tar.gz) shows this.

The background here is that I created the example to check alignment of C types is as expected, in my case checking that GCC and Poly/ML use the same alignment on my platform.  I did this by creating C functions with a struct argument whose first field is a char and second field is another C type.  These C functions cast each field to an int and return their sum.  Poly/ML calls the functions with a value of 1 for each field and checks that the result is 2.

**Comment by dcjm** [comment]
Thanks for reporting this.  I've commited a fix c3c107f . I put the wrong issue number in the commit message so it didn't match up.  The rules for structs in the SysV X86/64 API are complex and there was an error in one of the tests.
