### ISSUE TITLE
polyc doesn't compile

### ISSUE THREAD

**Issue by JeysonFlores** [polyml/polyml#161]
Hello I have this `main.sml` file:
```SML
 fun main() = print "Hello World\n";
 
 main();
```
if I execute it as `poly --script main.sml` it works however if I try to compile it with `polyc main.sml` it gives me this error:
```cmd
/usr/bin/ld: can't find -lpolyml
collect2: error: ld returned 1 exit status
```
I installed polyml through `sudo apt install polyml` on Ubuntu 20.04. Thanks

**Comment by JeysonFlores** [comment]
@melted @dcjm Thanks now it works!

**Comment by pclayton** [comment]
> It would probably make more sense to include `polyc` with `libpolyml-dev`, then. `polyc` isn't much use without the ability to link to `libpolyml`.

The same goes for `polyml.pc`.

As noted in [this comment](https://github.com/giraffelibrary/giraffe/issues/2#issuecomment-941610393), It looks like none of the Ubuntu packages currently provides `polyml.pc`.  That is an unfortunate oversight.
