### ISSUE TITLE
configure fails on MacPorts builders for arm

### ISSUE THREAD

**Issue by pclayton** [polyml/polyml#165]
The MacPorts builders for arm platforms are failing at the configure stage.

The status of the MacPorts builds for Poly/ML can be seen at https://ports.macports.org/all_builds/?port_name=polyml and, at the time of writing this issue, the builds on 2021-12-02 are for Poly/ML 5.9.

The builders for arm are 11.arm64 and 12.arm64.

11.arm64 fails with the following error from configure ([log](https://build.macports.org/builders/ports-11_arm64-builder/builds/36520/steps/install-port/logs/stdio), [saved text log](https://github.com/polyml/polyml/files/7641532/11.arm64-stdio.txt))

```
checking build system type... Invalid configuration `arm64-apple-darwin20': machine `arm64-apple' not recognized
configure: error: /bin/sh ./config.sub arm64-apple-darwin20 failed
Command failed:  cd "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_polyml/polyml/work/polyml-5.9" && ./configure --prefix=/opt/local --mandir=/opt/local/share/man --build=arm64-apple-darwin20 --enable-shared 
Exit code: 1
```

12.arm64 fails similarly with the following error from configure ([log](https://build.macports.org/builders/ports-12_arm64-builder/builds/30927/steps/install-port/logs/stdio), [saved text log](https://github.com/polyml/polyml/files/7641544/12.arm64-stdio.txt))
```
checking build system type... Invalid configuration `arm64-apple-darwin21': machine `arm64-apple' not recognized
configure: error: /bin/sh ./config.sub arm64-apple-darwin21 failed
Command failed:  cd "/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_polyml/polyml/work/polyml-5.9" && ./configure --prefix=/opt/local --mandir=/opt/local/share/man --build=arm64-apple-darwin21 --enable-shared 
Exit code: 1
```
The difference between these outputs is `arm64-apple-darwin20` vs. `arm64-apple-darwin21`.

**Comment by dcjm** [comment]
Running `configure` on a Mac M1 works fine so that would suggest that this is an issue with the MacPorts environment but I'm not really a Mac user.  A search for this on the net suggests that there is a problem with a non-standard `uname` returning `arm64` instead of `arm`. I've updated `config.guess` and `config.sub` which some reports suggest as a problem.

**Comment by pclayton** [comment]
I've seen some [comments](https://github.com/carlosonunez/obs-installer-for-apple-silicon/issues/1) that `uname -p` can report either `arm` or `arm64`.  (There seems to be general agreement that `uname -m` reports `arm64`.)  [One comment](https://github.com/pyca/pynacl/issues/657#issuecomment-969420932) suggests that the different results for the `-p` flag are due to the version of uname: macOS native uname (/usr/bin/uname) reports `arm` whereas coreutils uname reports `arm64`.  However, I am not able to control the path on the MacPorts builder.

With the latest MacPorts branch, I have tried
```
./configure --build=arm64-apple-darwin21
```
which fails with the error
```
checking build system type... Invalid configuration `arm64-apple-darwin21': machine `arm64-apple' not recognized
configure: error: /bin/sh ./config.sub arm64-apple-darwin21 failed
```
Although this is on my Linux machine, configure should still work, and does if I change the option to `--build=arm-apple-darwin21`.

A config.sub with a timestamp no earlier than 2020-07-10 looks like it would resolve this matter given [this update(http://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=commitdiff;h=a9323950d2b2c799e8c0d71d27b6208cbc6b9b96).

**Comment by dcjm** [comment]
The time stamps of `config.guess` and `config.sub` are now 2020-11-07 which should fix this.  For some reason Debian, which is what I normally use to build the config files, has its own versions of `config.guess` and `config.sub `that date from 2018 rather than using the upstream versions.  Are you able to test this branch before I merge it into master?

**Comment by pclayton** [comment]
I don't have an M1 Mac to check this.  The MacPorts builders run only on ports have have been merged - even the Github pre-commit checks don't test on an M1.  I can submit an update to the portfile with a patch containing changes from the MacPorts branch and once that is merged we should get results from the M1 builders, if you don't mind waiting for that.

**Comment by pclayton** [comment]
In creating patches for the port, I've noticed a couple of things about the MacPorts branch:

1. It contains the commit a63f2196a5e75edf1b0ca0e1e606562b0d09766e with the message "Fix incorrect argument when printing byte code assembly code." which isn't in master.  This commit looks like nothing to do with the MacPorts issues and I suspect you haven't yet pushed it from your master to Github.
2. The file `compile` used to be a symbolic link but is now a normal file.  Is that intended?  (It would make sense, as the other files generated by `autoreconf` are normal files.)  I don't think it matters for this MacPorts branch but I will include it anyway for consistency.

**Comment by pclayton** [comment]
It seems that Darwin's `patch` utility doesn't allow a symbolic link to be replaced with a file, so the patch for this leave `compile` as a symbolic link, which should be fine.  (GNU `patch` does support this but the MacPorts `port` utility uses `/usr/bin/patch`.)

**Comment by pclayton** [comment]
The [port health](https://ports.macports.org/port/polyml/details/) shows that MacPorts builders with arm64 processors now build successfully.

**Comment by dcjm** [comment]
Thanks for testing this.  I've merged the changes and deleted the MacPorts branch.
