### ISSUE TITLE
Superfluous symlink to /usr/share in the tarball

### ISSUE THREAD

**Issue by GergelyBuday** [polyml/polyml#169]
On git bash on Windows 10, I tried to extract the tarball and got an error message that it cannot create a symlink to /usr/share/...

Here is a full description:

https://unix.stackexchange.com/questions/688135/extracting-a-symlink-containing-tarball-on-git-bash

As a quick fix, I managed to extract it on a proper Unix and repackaged it with tar, which I could extract on git bash.

But I wonder why is there a symlink in the official tarball to a system directory.

This is true to 5.8.2 and 5.9.

**Comment by GergelyBuday** [comment]
Actually, I needed to remove the "compile" link at the root of the tarball and everything worked.

**Comment by pclayton** [comment]
The file `compile` changed from a symbolic link to a normal file in commit cae32f905095a98aeaeca02161a1ddd397cd9c6d, which happened since 5.9, so a tarball generated from master should avoid the issue.

**Comment by dcjm** [comment]
I think this came about because `automake --add-missing` creates a symlink by default unless `--copy` is also given.  Since this has now been fixed in master I'm closing this.
