### ISSUE TITLE
Poly ML 5.9 is infected with Binary.Trojan.Bulz

### ISSUE THREAD

**Issue by SirClickALot** [polyml/polyml#179]
I have some pretty tight security running on my HP laptop and when I attempt to open the ``PolyML5.9-64bit ``  installer for Windows, I am told that...

> HP Sure Click has detected that PolyML5.9-64bit.msi is malicious ...
Malware name: Binary.Trojan.Bulz

I took a quick look at v5.8 MSI and that doesn't seem to be infected but I'm put off from installing any version now until I can be more confident.

Can anyone verify?

**Comment by melted** [comment]
My antivirus doesn't complain, but that obviously is just one data point. So I checked it out with Virustotal, [link](https://www.virustotal.com/gui/file/4385592f9854f5dca1fee5abba9a322d146ebc99cb1409e66f80a620714b017c), and sure enough there are some antivirus engines that complain. But I would write it off as a false positive, because it's just a few and the biggest ones don't.

**Comment by SirClickALot** [comment]
Mmm...
I'm still cautious and I'm sure others will be too - something has clearly changed between v5.8 and v5.9

Can we, should try to somehow check what's changed that might be causing the potential false +ve?

Like I said, it's enough for me to stand well back and that's a real shame since I think the PolyML might really what I have been looking for.

Thanks

**Comment by dcjm** [comment]
I can understand why you're hesitant. There is always the possibilty that it has become infected but the likelihood is that it is a false positive. There have been a lot of changes between 5.8 and 5.9 as well as changes to Visual Studio and WiX (used to build the installer). Which scanners did you use? Are any of them freely available in a way that I could use them to narrow down the problem?

If you're concerned you could always build Poly/ML from source. The simplest way is to the Visual Studio Community edition which is free for personal and open-source use.

**Comment by SirClickALot** [comment]
I bit the bullet and let `PolyML5.9-64bit` through the HP Secure Click block and then scanned it with my local version of [Sophos Home](https://support.home.sophos.com/hc/en-us) and the latter said that it was safe! So, I'm going to conclude that it is indeed safe and that HP's SureClick was being a bit over zealous.
