### ISSUE TITLE
Conversion from string to real doesn't accept non-finite values

### ISSUE THREAD

**Issue by pclayton** [polyml/polyml#180]
In the Basis Library, in signature REAL, the description of `scan` and `fromString` [states](https://smlfamily.github.io/Basis/real.html#SIG:REAL.scan:VAL):

> It also accepts the following string representations of non-finite values:
> [+~-]?(inf | infinity | nan)
> where the alphabetic characters are case-insensitive.

However, these functions return `NONE` for any of these non-finite strings.

**Comment by dcjm** [comment]
It looks as though `IEEEReal.scan` correctly handles these cases.  I can't see any reason why `Real.scan` can't simply be defined in terms of `IEEEReal.scan` and `Real.fromDecimal`.  Can you see any subtle distinctions I've missed?

**Comment by pclayton** [comment]
I can't see any reason why the implementation can't be in terms of `IEEEReal.scan` and `Real.fromDecimal` either.  The format accepted by `IEEEReal.scan` is identical.  If `Option.composePartial (Real.fromDecimal, IEEEReal.fromString)` is equivalent, I would have expected the Basis Library to mention this, as such equivalences are usually mentioned.

I've noted some minor issues with `IEEEReal.scan` in https://github.com/polyml/polyml/issues/182.  

I ran a few performance tests and `Option.composePartial (Real.fromDecimal, IEEEReal.fromString)` is consistently 15-25% slower than `Real.fromDecimal` with greater variability in times, suggesting that GC may be greater.

**Comment by ttn-ttn** [comment]
I have noted that conversion from string to real overflows for values that are too large, however the description states that
> Values of too large a magnitude are represented as infinities; values of too small a magnitude are represented as zeros. 
which I understand as meaning that it should return an infinite value instead of overflowing. Is my understanding correct?

**Comment by dcjm** [comment]
I've started a new branch `IEEERealFixes` to track this and the other bugs and fixes.  `Tests/Succeed/Test198.ML` is intended to include regression tests for this so if you have cases that are handled incorrectly (or also any correct cases, for that matter) could you add them to that and send a pull request.
I've changed `Real.fromString` and `Real.scan` to use `IEEEReal.scan/fromString`.  It seems better to put all the special cases in one place even if it incurs an extra cost.

**Comment by pclayton** [comment]
This appears to be working well in the master branch.
