### ISSUE TITLE
How to compile binary files on Windows?

### ISSUE THREAD

**Issue by fenginsc** [polyml/polyml#185]
I know that I can use polyc to compile binaries on linux or macOS, but there is no polyc on windows, how do I compile them or is compiling binaries supported on windows? 
thanks.

**Comment by dcjm** [comment]
The difficulty of compiling on Windows is that there is no linker in the standard system. You can install Msys2 or Cygwin on Windows.  These provide command line interfaces under which you can run `polyc` as with Linux.

**Comment by fenginsc** [comment]
> The difficulty of compiling on Windows is that there is no linker in the standard system. You can install Msys2 or Cygwin on Windows. These provide command line interfaces under which you can run `polyc` as with Linux.

Thanks for your reply, I tried to compile it with Cygwin/Msys2, it worked and it works fine, but the only problem is that the compiled executable needs to have several dll dependencies attached to it to run, it is not a standalone single executable, I learned that I can use the mingw64-gcc provided by Msys2 to compile a standalone but it failed to compile, I have time to try again to see if it works.

**Comment by fenginsc** [comment]
After some attempts on my part, it finally failed, it won't compile into a standalone binary on windows, if you have any suggestions, appreciate it.

**Comment by dcjm** [comment]
By "standalone" do you mean independent of any DLL? That's difficult, maybe impossible.  However in Windows you can just put a copy of a DLL in the same directory as your executable and it will all work.

**Comment by fenginsc** [comment]
Yes, what I mean by "standalone" is that there is only one exe file and no need for other dll files, which seems to be impossible on windows at the moment, thank you for your reply, I put the dll file and exe file in the same folder and now it works fine.
