### ISSUE TITLE
Unable to compile from v5.9.1 release source on NetBSD 9.3 (amd64)

### ISSUE THREAD

**Issue by markwong** [polyml/polyml#191]
Unable to compile from v5.9.1 release source on NetBSD 9.3 (amd64)

Apparently the "polyimport" was the culprit.

The error message:

Making all in libpolymain
/bin/sh ../libtool  --tag=CC    --mode=compile gcc -DHAVE_CONFIG_H  -I. -I..    -Wall     -Wall -fno-strict-aliasing -O3 -MT polystub.lo -MD -MP -MF .deps/polystub.Tpo -c -o polystub.lo polystub.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -Wall -Wall -fno-strict-aliasing -O3 -MT polystub.lo -MD -MP -MF .deps/polystub.Tpo -c polystub.c  -fPIC -DPIC -o .libs/polystub.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -Wall -Wall -fno-strict-aliasing -O3 -MT polystub.lo -MD -MP -MF .deps/polystub.Tpo -c polystub.c -o polystub.o >/dev/null 2>&1
mv -f .deps/polystub.Tpo .deps/polystub.Plo
/bin/sh ../libtool  --tag=CC    --mode=link gcc    -Wall -fno-strict-aliasing -O3 -static -version-info 0:0  -o  libpolymain.la -rpath /extra/polyml/lib polystub.lo  -lpthread -lstdc++
libtool: link: ar cru .libs/libpolymain.a  polystub.o
libtool: link: ranlib .libs/libpolymain.a
libtool: link: ( cd ".libs" && rm -f "libpolymain.la" && ln -s "../libpolymain.la" "libpolymain.la" )
Making all in .
gcc -DHAVE_CONFIG_H -I.      -O3 -MT polyimport.o -MD -MP -MF .deps/polyimport.Tpo -c -o polyimport.o polyimport.c
mv -f .deps/polyimport.Tpo .deps/polyimport.Po
/bin/sh ./libtool  --tag=CC    --mode=link gcc  -O3     -o polyimport polyimport.o  libpolyml/libpolyml.la -lpthread -lstdc++
libtool: link: gcc -O3 -o .libs/polyimport polyimport.o  libpolyml/.libs/libpolyml.so -lpthread -lstdc++ -Wl,-rpath -Wl,/extra/polyml/lib
./polyimport  ./bootstrap/bootstrap64.txt -I . < ./bootstrap/Stage1.sml

Unable to initialise memory allocator
-H <Initial heap size (MB)>
--minheap <Minimum heap size (MB)>
--maxheap <Maximum heap size (MB)>
--gcpercent <Target percentage time in GC (1-99)>
--stackspace <Space to reserve for thread stacks and C++ heap(MB)>
--gcthreads <Number of threads to use for garbage collection>
--debug <Debug options: checkmem, gc, x>
--logfile <Logging file (default is to log to stdout)>
--exportstats <Enable another process to read the statistics>
Debug options:
checkmem <Perform additional debugging checks on memory>
gc <Log summary garbage-collector information>
gcenhanced <Log enhanced garbage-collector information>
gcdetail <Log detailed garbage-collector information>
memmgr <Memory manager information>
threads <Thread related information>
gctasks <Log multi-thread GC information>
heapsize <Log heap resizing data>
x <Log X-windows information>
sharing <Information from PolyML.shareCommonData>
locks <Information about contended locks>
rts <General run-time system calls>
saving <Saving and loading state; exporting>
*** Error code 1

Stop.
make[2]: stopped in /extra/src/polyml-5.9.1
*** Error code 1

Stop.
make[1]: stopped in /extra/src/polyml-5.9.1
*** Error code 1

Stop.
make: stopped in /extra/src/polyml-5.9.1

**Comment by dcjm** [comment]
I've had a look at this and I can see what the problem is.  NetBSD does not allow pages to be mapped with both WRITE and EXECUTE permissions so Poly/ML needs to work round this in order to be able to compile code on the fly.  It does this by creating a dummy file in `/tmp` and mapping this into memory at two different addresses.  It looks as though the file it is trying to create is too large for the temporary space.  I'll have a look at how to fix this properly but a temporary work-around is to modify line 176 in `libpolyml/memmgr.cpp` to reduce the size to, say, 100Mbytes.

**Comment by markwong** [comment]
Thank you @dcjm for the workaround suggestion. It is now compiled and working fine. Thanks!
