### ISSUE TITLE
Failure to build on recent ARM Silicon mac

### ISSUE THREAD

**Issue by mn200** [polyml/polyml#194]
`uname -a` gives 
```
Darwin michaeln-mbp2021 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000 arm64
```
When making from a recent `git` (90c0dbb2514e), `make` gets as far as bootstrap stage 7/7 and eventually fails with:
```
Use: basis/TopLevelPolyML.sml
******Writing object code******
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -O3   -o poly  polyexport.o  libpolymain/libpolymain.la libpolyml/libpolyml.la  -lstdc++ 
libtool: link: gcc -O3 -o .libs/poly polyexport.o  libpolymain/.libs/libpolymain.a libpolyml/.libs/libpolyml.dylib -lstdc++
ld: LINKEDIT overlap of start of LINKEDIT and symbol table in '/Users/michaeln/external-repos/polyml/polyexport.o' in '/Users/michaeln/external-repos/polyml/polyexport.o'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [poly] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by mn200** [comment]
I saw similar failures to build executables with an earlier hash, and am quite ready to blame an Xcode update I recently made.

**Comment by mn200** [comment]
I'm told that
> Xcode 15 (September 18, 2023), same linker error.
> Xcode 14.3.1 (June 1, 2023), seems to work

These are available from https://developer.apple.com/download/all/?q=xcode

**Comment by jhlchan** [comment]
I am a HOL4 users and get the same linker error when building HOL4 using the command:
```
poly < tools/smart-configure.sml
Poly/ML 5.9 Release
...
Making mllex
ld: LINKEDIT overlap of start of LINKEDIT and symbol table in '/private/var/folders/k5/_29n92td6yqcvzm2pf69n1n40000gn/T/polyobj.8335.o' in '/private/var/folders/k5/_29n92td6yqcvzm2pf69n1n40000gn/T/polyobj.8335.o'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Failed to make mllex (Fail "Command failed")
```
This happens when using Xcode 15, but no such error when reverting back to Xcode 14.3.1.

Some hints for fixing this bug:

Xcode 15 Release Notes\
[https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes)
```
Linking: New Features
A new linker has been written to significantly speed up static linking. It’s the default for all macOS, iOS, tvOS and visionOS binaries and anyone using the “Mergeable Libraries” feature. The classic linker can still be explicitly requested using -ld64, and will be removed in a future release.  (108915312)
```

**Comment by mn200** [comment]
Building with 
```
LDFLAGS=-ld64 ./configure 
```
seems to get everything to go through but attempts to use `polyc` then fail with 
```
/Users/michaeln/bin/polyc: line 43: g++ -std=gnu++11: command not found
```
stemming from the code in `polyc` calling "${LINK}", with `LINK` expanding to the `g++ -std=gnu++11`.

**Comment by mn200** [comment]
`polyc` also doesn't pick up the `LDFLAGS` change from the build process, but on my Mac at least, I can edit the `LINK` definition in `polyc` to remove the `-std=...` and to define `EXTRALDFLAGS` in the script file to be `-ld_classic` (preferred to `-ld64` according to the output), and then things seem to work once more.

**Comment by mn200** [comment]
I should have read #192 first; the handling of link options is nicer there.

**Comment by dcjm** [comment]
It looks as though the new linker doesn't like the object files that Poly/ML exports (libpolyml/machoexport.cpp).  I would hope that there's a fairly easy fix to this which would avoid the need to revert to the classic linker. It's probably something to do with the layout of the file. I'll do some experiments but if anyone can suggest what's wrong that would be helpful.

**Comment by binghe** [comment]
> It looks as though the new linker doesn't like the object files that Poly/ML exports (libpolyml/machoexport.cpp). I would hope that there's a fairly easy fix to this which would avoid the need to revert to the classic linker. It's probably something to do with the layout of the file. I'll do some experiments but if anyone can suggest what's wrong that would be helpful.

Sorry, your code is too sophisticated to understand. All I can do  is the following text from Xcode 15 release notes [1] which sounds like some layout changes in Mach-O files:
```
Xcode now automatically generates intermediate text-based dynamic library (TBD) files for dynamic libraries and frameworks in your project. These stubs allow linker dependencies to be tracked more accurately, meaning changes which don’t change the set of exported symbols no longer require all transitive dependencies to relink, speeding up incremental builds.  (99972271)
```

[1] https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes

**Comment by dcjm** [comment]
As far as I can see the problem is in the object file being generated, in this case `polyexport.o`.  It is possible to examine it with the `otool` command and someone who is familiar with the Mach linker may spot an error.  I suspect that there is something that is not quite right but that hasn't caused any problems in the past.  For example, it may be that some of the sizes need to be rounded up to some multiple.  Using the classic linker, `-ld_classic` works round the problem but I'm concerned that at some point Apple may no longer support that and we'd be back to the present situation.

**Comment by binghe** [comment]
> I've pushed a fix for this and it now builds without a problem on the recent update of MacOS. It seems that the new linker is picky about the format of the object file and does not accept files that the old linker did. In particular it seems to want the symbol table and string table after the other data. I have not found any documentation about this and the only way to find it was to try various changes until it worked. Unfortunately this seems to be typical of Apple.

Thanks for your work. FYI, on older macOS (Ventura) with older Xcode versions (without `-ld_classic` support), `polyc` produces the following warning:
```
ld: warning: no platform load command found in '/private/var/folders/2_/w81bdn691x30355x_4l0sr280000gq/T/polyobj.21038.o', assuming: macOS
```
If you search "ld: warning: no platform load command found in" on Internet, there are several similar reports. I think this [one](https://github.com/crystal-lang/crystal/issues/13846#issuecomment-2040267952) is most informative.

**Comment by dcjm** [comment]
I saw this on the most recent update of MacOS and Xtools.  It seems to be due to the fact that the object file does not contain a `LC_BUILD_VERSION` section.  My feeling is that unless this causes problems it is better left alone.

**Comment by binghe** [comment]
> I saw this on the most recent update of MacOS and Xtools. It seems to be due to the fact that the object file does not contain a `LC_BUILD_VERSION` section. My feeling is that unless this causes problems it is better left alone.

Fair enough. It doesn't cause any problem as far as I can see.
