### ISSUE TITLE
Run out of store while reading 98M file

### ISSUE THREAD

**Issue by serpent7776** [polyml/polyml#195]
Error behaviour:
I'm getting random `Run out of store` error while reading a 98M file.

Expected behaviour:
I'd expect that reading such small file always completes successfully.

`test.sml`:

```sml
fun main () =
  let
    val f = TextIO.openIn "input"
    val s = TextIO.inputAll f
    val l = size s
  val () = print (Int.toString l)
  in () end
```

Steps to reproduce:

```sh
truncate -s 98M input
polyc -o test test.sml
while gdb --return-child-result -ex 'set breakpoint pending on' -ex 'b BroadcastInterrupt' -ex r -ex q --args ./test input;  do echo; done
```

After a while it'll print `Run out of store - interrupting threads` and break point will be hit.

Backtrace points to this place https://github.com/polyml/polyml/blob/326b50a52421358c8b7ee4b37f4fed5cd329f1ca/libpolyml/processes.cpp#L1025
It is followed by call to `Processes::ThreadExit(TaskData*)`

```
(gdb) bt
#0  0x00007ffff7f70640 in Processes::BroadcastInterrupt() () from /usr/lib/libpolyml.so.13
#1  0x00007ffff7f75093 in Processes::FindAllocationSpace(TaskData*, unsigned long, bool) () from /usr/lib/libpolyml.so.13
#2  0x00007ffff7f84e89 in X86TaskData::SetMemRegisters() () from /usr/lib/libpolyml.so.13
#3  0x00007ffff7f8efe1 in X86AsmSwitchToPoly () from /usr/lib/libpolyml.so.13
#4  0x0000000000000000 in ?? ()
```

**Comment by dcjm** [comment]
Thank you for constructing a reproducible example.  That has made finding the problem much easier.  The heap sizing code is really tuned for the allocation of large numbers of small cells and wasn't behaving well when allocating a large buffer when the heap was very small.
