### ISSUE TITLE
[Feature request] Add output redirection as input for Windows

### ISSUE THREAD

**Issue by ItachiSan** [polyml/polyml#2]
As in title; Linux builds of PolyML support natively output redirection as input, while Windows does not.
It would be nice to be able to run commands like:
```
HD:\path\to\executable\PolyML.exe < HD:\path\to\file\input.sml
```
or something like
```
HD:\path\to\executable\PolyML.exe /flag_to_pass_input_file HD:\path\to\file\input.sml
```
As it would be really easy to add shortcuts in advanced text editors (e.g. Notepad++) or creating CMD wrappers to simplify users life.

**Comment by dcjm** [comment]
This works for me with the current release (5.5.2).  For example:
```
"c:\Program Files (x86)\Poly ML\PolyML.exe" < input.sml > output.txt
```
does exactly what one would expect.

There is also a --use argument that takes a file name and compiles and runs it before the main read-eval-print loop is started.  If that file calls OS.Process.exit the main loop will never entered

If you want to discuss this further please use the Poly/ML mailing list.
