### ISSUE TITLE
Discussion: switch to C++11 threads in thread library

### ISSUE THREAD

**Issue by eatonphil** [polyml/polyml#41]
Would it make sense to switch to the thread library introduced into C++11 from the current method of explicitly using Windows threads or pthreads in the Poly/ML thread library? The C++ library abstracts away these differences. Among many other similar questions, [here](http://stackoverflow.com/questions/25221247/c11-stdthread-vs-windows-createthread) is a Stackoverflow thread discussing why it makes sense to use the C++ thread library over Windows threads.

Would a branch using the C++ thread library be worth reviewing?

**Comment by dcjm** [comment]
If we were starting from scratch there may well be a case for using this but given the existing code I'm not convinced that a change would be warranted.  I'd be concerned that people using older systems would be unable to build Poly/ML.

**Comment by eatonphil** [comment]
Ok. Thanks!
