### ISSUE TITLE
compile error with gcc4.8.2

### ISSUE THREAD

**Issue by eldesh** [polyml/polyml#43]
I am using linux(i386) & g++ 4.8.2 .
Build master (f0b2353) fails on error:

```
basicio.cpp: In function 'SaveVecEntry* IO_dispatch_c(TaskData*, Handle, Handle, Handle)':
basicio.cpp:1655:28: error: 'SIZE_MAX' was not declared in this scope
                 if (size > SIZE_MAX / 2) raise_fail(taskData, "getcwd needs too large a buffer");
                            ^
```

SIZE_MAX is defined for C++11(and C99), but not for C++03.

**Comment by jrtc27** [comment]
Ah. If you replace `SIZE_MAX` with `std::numeric_limits<size_t>::max()` everywhere, does it then compile?

**Comment by eldesh** [comment]
I inserted ```#include <limits>``` and replace ```SIZE_MAX``` with ```std::numeric_limits<size_t>::max()```,
then build succeeded.
Changed files are basicio.cpp, network.cpp, and statistics.cpp .

**Comment by dcjm** [comment]
I've made that change.  Could you check that it now compiles for you.

**Comment by eldesh** [comment]
I confirmed it (2e40cad) compiles on my env :+1:
