### ISSUE TITLE
Port MLTON 'MLBasis' to polyml

### ISSUE THREAD

**Issue by bikallem** [polyml/polyml#45]
Hi,
Is there any interest in porting [MLTON basis](http://mlton.org/MLBasis]system) to polyml? 
It seems there are other SML libs/software that frequently target the use of MLBasis or SMLNJ CM. Right now MLTON lacks a REPL/toplevel and it seems SML developers frequently use both SMLNJ(for REPL/toplevel) and MLTON (for producing release builds). polyml could possibly be used as repl/toplevel along with MLTON if polyml were to support MLBasis file. This will also make porting and/or using MLBasis projects under polyml much more productive and straightforward in most cases.

**Comment by dcjm** [comment]
It would be nice to have this but it's a question of having the time to do the work.  Are you interested in doing it yourself?  I'm happy to advise on the Poly/ML side of things.
David

**Comment by eatonphil** [comment]
Out of curiosity, if someone *is* interested in porting the ML Basis system what would it require?

**Comment by bikallem** [comment]
Closing this for now.
