### ISSUE TITLE
Hiccups when processing many files in sequence

### ISSUE THREAD

**Issue by andry-tino** [polyml/polyml#54]
This looks like being a know issue reported [here](http://lists.inf.ed.ac.uk/pipermail/polyml/2016-April/001839.html). Reporting here for two reasons:

- This is the repository, thus this is the place for issues reporting and following :)
- I have better repro steps than those reported in the linked reported issue.

### (Quasi)Stable repro steps
In order to repro the issue, it is possible to follow the build scripts of [HOL](https://github.com/HOL-Theorem-Prover/HOL/blob/master/INSTALL) (the section where `poly` is used for building).

1. I am operating on a Unix machine running CentOS.
2. I have successfully forked and build [PolyML](https://github.com/polyml/polyml).
3. I have followed indications [here](https://github.com/HOL-Theorem-Prover/HOL/blob/master/INSTALL) for building HOL.
4. Ran `polyml < tools/smart_configure.sml`.
5 Ran `./bin/build`.
6. I could actually SUCCESSFULLY build.

The problem is that when running `./bin/build`, sometimes the build process would fail with this message when building a specific library in the list:

> Building directory src/temporal/src [23 Apr, 19:20:18]
> Temporal_Logic    : Holmake: Fail exception: Unknown result status
> Build failed in directory /home/myuser/Git/HOL/src/temporal/src (exited with code 1)

This happened many times. When this happened, I would call `./bin/build` again which would skip all built parts and resume building from where he had the last failure. All until I could build everything.

### Final notes
The root cause seems like being explained already in the linked bug. This bug has also been reported [here at HOL](https://github.com/HOL-Theorem-Prover/HOL/issues/337#issuecomment-213841586) and closed as external issue.

**Comment by jrtc27** [comment]
Should be fixed by https://github.com/polyml/polyml/commit/ba608ceb1dbc20db934bd01b0bccdd50c08ac4e9.

**Comment by andry-tino** [comment]
It got committed 2 days ago, so probably it got fixed. Let me verify this after syncing...
