### ISSUE TITLE
cross-compiling for win32/win64 from linux mingw?

### ISSUE THREAD

**Issue by ryu0** [polyml/polyml#60]
I've been experimenting with this and I found that most of the process can be done on a Linux host but that 2 make targets require the host to be Windows, because it is using the built binaries to do something. I assume this is something not easily changed to allow true cross-compiling. But then I don't know this project too well. Thoughts?

**Comment by dcjm** [comment]
Poly/ML is a compiler for Standard ML that is mostly written in ML.  That means that there are bootstrapping issues.  There needs to be an ML compiler to compile in the Basis library.
The build process first builds the run-time system and when that is complete it runs it to load in a pre-built compiler.  That then runs and compiles in the library, outputting an object file containing the original compiler and the library.  This is linked with the run-time system to produce the final poly.
I can't see how this could be cross-compiled and I'm not really sure why one would want to.

**Comment by ryu0** [comment]
Ah, well that explains it then. I could see a benefit of cross-compiling in being able to automate builds for binary distributions from a single host, but that isn't strictly required. Thanks for clearing that up.
