### ISSUE TITLE
hexadecimal constants starting with 0X not accepted

### ISSUE THREAD

**Issue by ryu0** [polyml/polyml#65]
According to "elements of ml programming", hexadecimal constants should be accepted whether they start with 0x or 0X, but polyml 5.6 only accepts them if they start with 0x. This seems like a bug to me. Thoughts?

See:
>Poly/ML 5.6 Release
> 0xAA;
val it = 170: int
> 0XAA;
poly: : error: Value or constructor (XAA) has not been declared Found near 0 XAA
poly: : error: Type error in function application.
   Function: 0 : int
   Argument: XAA : bad
   Reason: Value being applied does not have a function type
Found near 0 XAA
Static Errors

**Comment by dcjm** [comment]
The Definition of Standard ML (Revised) is quite specific:  

> An _integer constant (in hexadecimal notation)_ is an optional negation symbol followed by 0x followed by a non-empty sequence of hexadecimal digits.

There is no mention of 0X so clearly this should be parsed as the constant 0 followed by the identifier X.

**Comment by ryu0** [comment]
Strange. The Standard Basis defines this pattern under the Int structure's scan function, located here: http://sml-family.org/Basis/integer.html#SIG:INTEGER.scan:VAL
 
[+~-]?(0x | 0X)?[0-9a-fA-F]+

So then, the basis is able to accept them with 0X, but the actual definition is defined differently? How strange.

**Comment by dcjm** [comment]
`Int.scan StringCvt.HEX` is defined to handle a wider range of hexadecimal input than are allowed in the ML language.
```
> StringCvt.scanString (Int.scan StringCvt.HEX) "-0XaBc";
val it = SOME ~2748: int option

```
From a quick check I've made neither SML/NJ nor Hamlet allow 0X in ML itself.

**Comment by ryu0** [comment]
Huh. Okay, then it appears my book is mistaken. It says the prefix may be 0x or 0X. Obviously this is not the case.
