### ISSUE TITLE
`Socket.accept` returns even when connection isn't incoming

### ISSUE THREAD

**Issue by KeenS** [polyml/polyml#67]
(I'm new to Poly/ML so I may missing somthing.)

Here is a reproduction code

``` sml
fun main () = let
    val address = "127.0.0.1"
    val port = 8080
    val sock = INetSock.TCP.socket ()
    val () = Socket.bind (sock, INetSock.any port)
    val () = Socket.listen (sock, 128)
    val (conn, remote) = Socket.accept sock
    val (in_addr, port) = INetSock.fromAddr remote
in
    print ((NetHostDB.toString in_addr) ^ "\n")
end
```

compile, run this, and wait 4, 5 seconds and you will get such output

```
192.168.1.1
```

Address `192.168.1.1` is't my box's id address and since I bound to `127.0.0.1` , it can't happen that connection from `192.168.1.1` is incomming.

my environment is

```
$ uname -a
Linux T440p 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
$ poly
Poly/ML 5.6 Release (Git version v5.6)
```

poly is compiled with `--with-threads` flag.

**Comment by dcjm** [comment]
You have bound to any address, not 127.0.0.1.  You're not actually using `address` anywhere.  Presumably whatever machine is using 192.168.1.1 is sending periodic requests to port 8080 on your machine.

**Comment by KeenS** [comment]
Oops, it's my mistake, thank you.
BTW, I tried to use `INetSock.toAddr` and it seems address is parsed incorrecty.

```sml
fun main() = let
    val address = "127.0.0.1"
    val port = 8080
    val addr = INetSock.toAddr(Option.valOf (NetHostDB.fromString(address)), port)
    val (address2, port2) = INetSock.fromAddr addr
in
    print (address ^ " -> " ^ (NetHostDB.toString address2) ^ "\n")
end

```
127.0.0.1 -> 0.0.0.127
```

I tried othen cases and got these results

```
127.0.0.12 -> 0.0.0.127
1.0.0.127 -> 0.0.0.1
127.2.0.12 -> 0.0.127.2
127.2.3.12 -> 127.2.3.12
192.168.1.1 -> 192.168.1.1
```

Maybe having trouble with `0` ?

**Comment by dcjm** [comment]
There was a bug in the the handling a zero that should now have been fixed.
