### ISSUE TITLE
tag past releases

### ISSUE THREAD

**Issue by johnyf** [polyml/polyml#70]
Please tag previous releases, namely those listed at SourceForge, under [`Files/Home/polyml`](https://sourceforge.net/projects/polyml/files/polyml/). This will enable checking out older releases after cloning, and building directly from the repository, without the need to visit SourceForge (something that can easily go unnoticed).

This issue arose when I needed `polyml == 5.2.1` for building [Isabelle 2011-1](http://isabelle.in.tum.de/website-Isabelle2011-1/download.html), and `polyml == 5.6` (installed with `apt-get`) wasn't compatible (syntax errors were being raised).

**Comment by dcjm** [comment]
I guess that could be useful so I've added the tags.

**Comment by johnyf** [comment]
Thank you very much!
