### ISSUE TITLE
XWindows and Motif bindings broken

### ISSUE THREAD

**Issue by dj3vande** [polyml/polyml#71]
Attempting to configure and build the current master with `--with-x` on MacOS 10.10.5, the build fails with:
```
xwindows.cpp:4795:58: error: use of undeclared identifier 'POLY_SYS_XWindows'
                process_may_block(taskData, display->fd, POLY_SYS_XWindows);
                                                         ^
xwindows.cpp:4820:21: error: use of undeclared identifier 'POLY_SYS_XWindows'
                    POLY_SYS_XWindows);
                    ^
2 errors generated.
make[2]: *** [xwindows.lo] Error 1       
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Since `process_may_block` doesn't actually use its last argument, removing it allows the build to proceed past here, but it fails later on with:
```
mlsource/extra/XWindows/XCall.ML:24: error: Value or constructor (run_call1) has not been declared in structure RunCall
Found near RunCall.run_call1 RuntimeCalls.POLY_SYS_XWindows n
mlsource/extra/XWindows/XCall.ML:24: error: Structure (RuntimeCalls) has not been declared
Found near RunCall.run_call1 RuntimeCalls.POLY_SYS_XWindows n 
Exception- Fail unexpectedly raised while compiling

mlsource/extra/XWindows was not declared
make[2]: *** [polyexport.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

This appears to have been missed in the rework of the RTS since 5.6 that removed `RuntimeCalls`; attempting to configure and build from the 5.6 tag with `--with-x` builds as expected (I haven't gotten to exercising it at runtime).

Full configure+build log: https://gist.github.com/dj3vande/46e973e1dac14bdc3c43cb08b8a06ac3 (diff for `xwindows.cpp` is at line 900)

**Comment by dcjm** [comment]
I've committed fixes for the run-time system and the ML code and it now builds and runs a simple example.  I haven't tried anything more than that so if there are still problems please open a new issue.

**Comment by dj3vande** [comment]
Thanks!
My (fairly simple so far) programs now build and run with the latest master as well.
