### ISSUE TITLE
"Too many fixups" error from linker causing polyc to fail

### ISSUE THREAD

**Issue by mn200** [polyml/polyml#75]
I am getting the following on macOS 10.12.2:

```
$ polyc -o munge.exe munge.sml
.... some top-level output of mine from munge.sml ....
ld: in section __TEXT,__text reloc 6517489: too may fixups in Redblackmap.K(1)(1) file '/var/folders/r1/m3p_k_cd2_79p1b96hgbgggx06hfs_/T//polyobj.8673.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Is there a workaround?

**Comment by dcjm** [comment]
Searching for "too may fixups" (sic) finds references to the code of the Mac OS X linker but not much else.  It looks as though the limit is 2^24.  I'm guessing that fixups here means relocations.  Does your code export a large data structure?  A relocation is needed whenever a cell contains the address of something else.  Using vectors rather than lists will reduce the number of addresses.  Alternatively you may be able to use PolyML.SaveState.saveState/loadState to export and import the data structure.

**Comment by mn200** [comment]
For the sake of documentation: as of 5.7 and 5.7.1, `SaveState` functions in combination with `shareCommonData` seemed to fix this issue for us.

**Comment by mn200** [comment]
@AndreasLoow's issue (reported in HOL) referenced above suggests that our more aggressive use of `shareCommonData` only served to ameliorate the issue and that it remains.  Apparently:

> This is an internal limit in the linker.  The linker breaks up .o files into seperate functions (for dead code stripping and order files).  Each function has a limit of 16M (2^24) fixups.  Either munge.exe0.o has one huge function, or it is machine generated (by something other than clang) and is not using .subsection_via_symbols which tells the linker there are no fall through functions and each non-local label is the start of a new (independent) function.

(from Apple).

**Comment by dcjm** [comment]
I've comitted a fix for this, 9f6ed77, or at least something that fixes my simple test:
`val l = ref(List.tabulate(40000000, fn i => i));
fun main _ = print(Int.toString(hd(! l)));
`
I'd assumed that the problem was that the limit was on the total number of relocations but since the limit is per segment it is possible to fix it by limiting the size of a segment and hence the number of addresses in it.  Please try this and let me know whether or not it fixes it in your tests.

**Comment by dcjm** [comment]
That's odd.  Do you have the ".o" file that causes the problem?  Could you send me the output of `otool -l file.o`

**Comment by AndreasLoow** [comment]
Here's the output:

```
> otool -l munge.exe0.o
munge.exe0.o:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x00           1     2        656 0x00000000
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 632
  segname
   vmaddr 0x0000000000000000
   vmsize 0x00000000070a1340
  fileoff 0
 filesize 118100800
  maxprot 0x00000007
 initprot 0x00000007
   nsects 7
    flags 0x0
Section
  sectname __const
   segname __DATA
      addr 0x00000000000000f0
      size 0x0000000006e99410
    offset 57785996
     align 2^3 (8)
    reloff 688
    nreloc 7183412
     flags 0x00000100
 reserved1 0
 reserved2 0
Section
  sectname __text
   segname __TEXT
      addr 0x0000000006e99500
      size 0x00000000001c1d98
    offset 173757084
     align 2^3 (8)
    reloff 57467984
    nreloc 25316
     flags 0x00000500
 reserved1 0
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x000000000705b298
      size 0x0000000000037ee0
    offset 175599668
     align 2^3 (8)
    reloff 57670512
    nreloc 14154
     flags 0x00000100
 reserved1 0
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x0000000007093178
      size 0x0000000000000120
    offset 175828756
     align 2^3 (8)
    reloff 57783744
    nreloc 4
     flags 0x00000100
 reserved1 0
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x0000000007093298
      size 0x000000000000da40
    offset 175829044
     align 2^3 (8)
    reloff 57783776
    nreloc 0
     flags 0x00000100
 reserved1 0
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x00000000070a0cd8
      size 0x0000000000000668
    offset 175884916
     align 2^3 (8)
    reloff 57783776
    nreloc 42
     flags 0x00000100
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __DATA
      addr 0x0000000000000000
      size 0x00000000000000f0
    offset 57785756
     align 2^3 (8)
    reloff 57784112
    nreloc 8
     flags 0x00000500
 reserved1 0
 reserved2 0
Load command 1
     cmd LC_SYMTAB
 cmdsize 24
  symoff 57784176
   nsyms 43
  stroff 57784864
 strsize 891
```

**Comment by dcjm** [comment]
The limit seems to be around 6M rather than 16M unless there's something else that isn't being taken into account.  I've reduced the size in another commit 0f0619c.  See if this works.  If not I may have to reduce it further or try something else.

**Comment by AndreasLoow** [comment]
Thanks! I am able to link `munge.exe.o` now!
