### ISSUE TITLE
Narrowing conversion error

### ISSUE THREAD

**Issue by jamesjer** [polyml/polyml#77]
On ppc64 and ppc64le platforms, we are encountering the following build failure with gcc 6.3.1 when building polyml for Fedora:

unix_specific.cpp:361:1: error: narrowing conversion of '2147483648u' from 'unsigned int' to 'int' inside { } [-Wnarrowing]
 };
 ^

The offending constant is NOFLSH, which has the value 0x80000000, an unsigned value, on those two platforms.  Changing that to "(int)NOFLSH" lets the build complete, but I don't know if it will behave correctly at runtime.

**Comment by dcjm** [comment]
Is this 5.6 release or git master? There was a commit to git master a year ago to address the issue of NOFLSH on PPC.

**Comment by jamesjer** [comment]
This is 5.6.  Sorry, I didn't think to check whether master had a fix for the problem.
