### ISSUE TITLE
Segfault on Socket.recvVec on master

### ISSUE THREAD

**Issue by bacam** [polyml/polyml#80]
While porting some code to the polyml git master I found that it was segfaulting when reading from a socket, despite opening the socket and sending some data successfully.  A simpler test program is

```
let val s = INetSock.TCP.socket ()
    val ent = Option.valOf (NetHostDB.getByName "localhost")
    val addr = INetSock.toAddr(NetHostDB.addr ent, 1234)
    val _ = Socket.connect (s,addr)
in Socket.recvVec (s, 1)
end
```

It I run this alongside `nc -l localhost 1234`, when I send a character from nc it crashes.  I tried running it under gdb, and the actual native code appears to be fine, it looks like it is crashing in compiled code just afterwards.

This is all on Ubuntu 16.04 on x86-64.

**Comment by dcjm** [comment]
This was actually a problem with Word8ArraySlice.vector that is used to return the result.  Now fixed.  Thanks for reporting it.
