### ISSUE TITLE
compiled program fails silently on Io exception

### ISSUE THREAD

**Issue by wolfgangj** [polyml/polyml#81]
When I compile and run this program:
```
fun main() = (
    print "one\n";
    TextIO.openIn "file-which-does-not-exist";
    print "two\n"
)
```
This will print "one" and exit with error code 1 without printing any exception info. This makes it hard to find out what's wrong.

I'm on 64-bit ARM, in case that matters.

EDIT: Actually this applies to all exceptions, e.g.:

```
fun main() = (
    print "one\n";
    raise Fail "oops";
    print "two\n"
)
```

This also just prints "one" and exits with status 1.

**Comment by eatonphil** [comment]
I think this is expected behavior. You need to do explicit error handling yourself. Unless you're running it from the REPL.
