### ISSUE TITLE
Incorrect use of raise_syscall in process_may_block

### ISSUE THREAD

**Issue by Smattr** [polyml/polyml#93]
libpolyml/xwindows.cpp:process_may_block contains the following code:

```cpp
else if (selRes < 0 && errno != EINTR) // Maybe another thread closed descr
    raise_syscall(taskData, "select failed %d\n", errno);
```

This is using `raise_syscall` as if it takes a format argument, but it really just takes a string. Should we just drop the ` %d` from the string?

**Comment by dcjm** [comment]
That doesn't look right so it should be changed.  This is really legacy code.  It looks like it hasn't been updated when changes were made elsewhere.
