### ISSUE TITLE
Double release of scheduler lock when creating task data

### ISSUE THREAD

**Issue by Smattr** [polyml/polyml#94]
While hacking on some of the locking code, I noticed around line 1200 in processes.cpp, we have:

```cpp
PLocker lock(&schedLock);
...
        if (newArray)
        {
...
        }
        else
        {
            delete(taskData);
            schedLock.Unlock();
            throw MemoryException();
        }
```

It looks to me like the explicit unlock of `schedLock` is incorrect when the `PLocker` `lock` will unlock it when we exit the function. This path is only reached when `realloc` fails, so it is probably rarely hit. OTOH perhaps I am misunderstanding the logic of this function?

**Comment by dcjm** [comment]
Yes, you're right.  I think I replaced some explicit locking and unlocking by PLocker at some point and forgot to remove that.  Probably taskArray should be replaced by by std::vector.
